// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// CodeSigningConfigSpec defines the desired state of CodeSigningConfig.
//
// Details about a Code signing configuration (https://docs.aws.amazon.com/lambda/latest/dg/configuration-codesigning.html).
type CodeSigningConfigSpec struct {

	// Signing profiles for this code signing configuration.
	// +kubebuilder:validation:Required
	AllowedPublishers *AllowedPublishers `json:"allowedPublishers"`
	// The code signing policies define the actions to take if the validation checks
	// fail.
	CodeSigningPolicies *CodeSigningPolicies `json:"codeSigningPolicies,omitempty"`
	// Descriptive name for this code signing configuration.
	Description *string `json:"description,omitempty"`
}

// CodeSigningConfigStatus defines the observed state of CodeSigningConfig
type CodeSigningConfigStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// Unique identifer for the Code signing configuration.
	// +kubebuilder:validation:Optional
	CodeSigningConfigID *string `json:"codeSigningConfigID,omitempty"`
	// The date and time that the Code signing configuration was last modified,
	// in ISO-8601 format (YYYY-MM-DDThh:mm:ss.sTZD).
	// +kubebuilder:validation:Optional
	LastModified *string `json:"lastModified,omitempty"`
}

// CodeSigningConfig is the Schema for the CodeSigningConfigs API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type CodeSigningConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              CodeSigningConfigSpec   `json:"spec,omitempty"`
	Status            CodeSigningConfigStatus `json:"status,omitempty"`
}

// CodeSigningConfigList contains a list of CodeSigningConfig
// +kubebuilder:object:root=true
type CodeSigningConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CodeSigningConfig `json:"items"`
}

func init() {
	SchemeBuilder.Register(&CodeSigningConfig{}, &CodeSigningConfigList{})
}
