//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountLimit) DeepCopyInto(out *AccountLimit) {
	*out = *in
	if in.CodeSizeUnzipped != nil {
		in, out := &in.CodeSizeUnzipped, &out.CodeSizeUnzipped
		*out = new(int64)
		**out = **in
	}
	if in.CodeSizeZipped != nil {
		in, out := &in.CodeSizeZipped, &out.CodeSizeZipped
		*out = new(int64)
		**out = **in
	}
	if in.TotalCodeSize != nil {
		in, out := &in.TotalCodeSize, &out.TotalCodeSize
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountLimit.
func (in *AccountLimit) DeepCopy() *AccountLimit {
	if in == nil {
		return nil
	}
	out := new(AccountLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountUsage) DeepCopyInto(out *AccountUsage) {
	*out = *in
	if in.FunctionCount != nil {
		in, out := &in.FunctionCount, &out.FunctionCount
		*out = new(int64)
		**out = **in
	}
	if in.TotalCodeSize != nil {
		in, out := &in.TotalCodeSize, &out.TotalCodeSize
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountUsage.
func (in *AccountUsage) DeepCopy() *AccountUsage {
	if in == nil {
		return nil
	}
	out := new(AccountUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Alias) DeepCopyInto(out *Alias) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Alias.
func (in *Alias) DeepCopy() *Alias {
	if in == nil {
		return nil
	}
	out := new(Alias)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Alias) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AliasConfiguration) DeepCopyInto(out *AliasConfiguration) {
	*out = *in
	if in.AliasARN != nil {
		in, out := &in.AliasARN, &out.AliasARN
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.FunctionVersion != nil {
		in, out := &in.FunctionVersion, &out.FunctionVersion
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.RevisionID != nil {
		in, out := &in.RevisionID, &out.RevisionID
		*out = new(string)
		**out = **in
	}
	if in.RoutingConfig != nil {
		in, out := &in.RoutingConfig, &out.RoutingConfig
		*out = new(AliasRoutingConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliasConfiguration.
func (in *AliasConfiguration) DeepCopy() *AliasConfiguration {
	if in == nil {
		return nil
	}
	out := new(AliasConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AliasList) DeepCopyInto(out *AliasList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Alias, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliasList.
func (in *AliasList) DeepCopy() *AliasList {
	if in == nil {
		return nil
	}
	out := new(AliasList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AliasList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AliasRoutingConfiguration) DeepCopyInto(out *AliasRoutingConfiguration) {
	*out = *in
	if in.AdditionalVersionWeights != nil {
		in, out := &in.AdditionalVersionWeights, &out.AdditionalVersionWeights
		*out = make(map[string]*float64, len(*in))
		for key, val := range *in {
			var outVal *float64
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(float64)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliasRoutingConfiguration.
func (in *AliasRoutingConfiguration) DeepCopy() *AliasRoutingConfiguration {
	if in == nil {
		return nil
	}
	out := new(AliasRoutingConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AliasSpec) DeepCopyInto(out *AliasSpec) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.FunctionName != nil {
		in, out := &in.FunctionName, &out.FunctionName
		*out = new(string)
		**out = **in
	}
	if in.FunctionRef != nil {
		in, out := &in.FunctionRef, &out.FunctionRef
		*out = new(corev1alpha1.AWSResourceReferenceWrapper)
		(*in).DeepCopyInto(*out)
	}
	if in.FunctionVersion != nil {
		in, out := &in.FunctionVersion, &out.FunctionVersion
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.RoutingConfig != nil {
		in, out := &in.RoutingConfig, &out.RoutingConfig
		*out = new(AliasRoutingConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliasSpec.
func (in *AliasSpec) DeepCopy() *AliasSpec {
	if in == nil {
		return nil
	}
	out := new(AliasSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AliasStatus) DeepCopyInto(out *AliasStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.RevisionID != nil {
		in, out := &in.RevisionID, &out.RevisionID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliasStatus.
func (in *AliasStatus) DeepCopy() *AliasStatus {
	if in == nil {
		return nil
	}
	out := new(AliasStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowedPublishers) DeepCopyInto(out *AllowedPublishers) {
	*out = *in
	if in.SigningProfileVersionARNs != nil {
		in, out := &in.SigningProfileVersionARNs, &out.SigningProfileVersionARNs
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowedPublishers.
func (in *AllowedPublishers) DeepCopy() *AllowedPublishers {
	if in == nil {
		return nil
	}
	out := new(AllowedPublishers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmazonManagedKafkaEventSourceConfig) DeepCopyInto(out *AmazonManagedKafkaEventSourceConfig) {
	*out = *in
	if in.ConsumerGroupID != nil {
		in, out := &in.ConsumerGroupID, &out.ConsumerGroupID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmazonManagedKafkaEventSourceConfig.
func (in *AmazonManagedKafkaEventSourceConfig) DeepCopy() *AmazonManagedKafkaEventSourceConfig {
	if in == nil {
		return nil
	}
	out := new(AmazonManagedKafkaEventSourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CORS) DeepCopyInto(out *CORS) {
	*out = *in
	if in.AllowCredentials != nil {
		in, out := &in.AllowCredentials, &out.AllowCredentials
		*out = new(bool)
		**out = **in
	}
	if in.AllowHeaders != nil {
		in, out := &in.AllowHeaders, &out.AllowHeaders
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AllowMethods != nil {
		in, out := &in.AllowMethods, &out.AllowMethods
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AllowOrigins != nil {
		in, out := &in.AllowOrigins, &out.AllowOrigins
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ExposeHeaders != nil {
		in, out := &in.ExposeHeaders, &out.ExposeHeaders
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.MaxAge != nil {
		in, out := &in.MaxAge, &out.MaxAge
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CORS.
func (in *CORS) DeepCopy() *CORS {
	if in == nil {
		return nil
	}
	out := new(CORS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeSigningConfig) DeepCopyInto(out *CodeSigningConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeSigningConfig.
func (in *CodeSigningConfig) DeepCopy() *CodeSigningConfig {
	if in == nil {
		return nil
	}
	out := new(CodeSigningConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CodeSigningConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeSigningConfigList) DeepCopyInto(out *CodeSigningConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CodeSigningConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeSigningConfigList.
func (in *CodeSigningConfigList) DeepCopy() *CodeSigningConfigList {
	if in == nil {
		return nil
	}
	out := new(CodeSigningConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CodeSigningConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeSigningConfigSpec) DeepCopyInto(out *CodeSigningConfigSpec) {
	*out = *in
	if in.AllowedPublishers != nil {
		in, out := &in.AllowedPublishers, &out.AllowedPublishers
		*out = new(AllowedPublishers)
		(*in).DeepCopyInto(*out)
	}
	if in.CodeSigningPolicies != nil {
		in, out := &in.CodeSigningPolicies, &out.CodeSigningPolicies
		*out = new(CodeSigningPolicies)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeSigningConfigSpec.
func (in *CodeSigningConfigSpec) DeepCopy() *CodeSigningConfigSpec {
	if in == nil {
		return nil
	}
	out := new(CodeSigningConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeSigningConfigStatus) DeepCopyInto(out *CodeSigningConfigStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.CodeSigningConfigID != nil {
		in, out := &in.CodeSigningConfigID, &out.CodeSigningConfigID
		*out = new(string)
		**out = **in
	}
	if in.LastModified != nil {
		in, out := &in.LastModified, &out.LastModified
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeSigningConfigStatus.
func (in *CodeSigningConfigStatus) DeepCopy() *CodeSigningConfigStatus {
	if in == nil {
		return nil
	}
	out := new(CodeSigningConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeSigningConfig_SDK) DeepCopyInto(out *CodeSigningConfig_SDK) {
	*out = *in
	if in.AllowedPublishers != nil {
		in, out := &in.AllowedPublishers, &out.AllowedPublishers
		*out = new(AllowedPublishers)
		(*in).DeepCopyInto(*out)
	}
	if in.CodeSigningConfigARN != nil {
		in, out := &in.CodeSigningConfigARN, &out.CodeSigningConfigARN
		*out = new(string)
		**out = **in
	}
	if in.CodeSigningConfigID != nil {
		in, out := &in.CodeSigningConfigID, &out.CodeSigningConfigID
		*out = new(string)
		**out = **in
	}
	if in.CodeSigningPolicies != nil {
		in, out := &in.CodeSigningPolicies, &out.CodeSigningPolicies
		*out = new(CodeSigningPolicies)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.LastModified != nil {
		in, out := &in.LastModified, &out.LastModified
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeSigningConfig_SDK.
func (in *CodeSigningConfig_SDK) DeepCopy() *CodeSigningConfig_SDK {
	if in == nil {
		return nil
	}
	out := new(CodeSigningConfig_SDK)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeSigningPolicies) DeepCopyInto(out *CodeSigningPolicies) {
	*out = *in
	if in.UntrustedArtifactOnDeployment != nil {
		in, out := &in.UntrustedArtifactOnDeployment, &out.UntrustedArtifactOnDeployment
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeSigningPolicies.
func (in *CodeSigningPolicies) DeepCopy() *CodeSigningPolicies {
	if in == nil {
		return nil
	}
	out := new(CodeSigningPolicies)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeadLetterConfig) DeepCopyInto(out *DeadLetterConfig) {
	*out = *in
	if in.TargetARN != nil {
		in, out := &in.TargetARN, &out.TargetARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeadLetterConfig.
func (in *DeadLetterConfig) DeepCopy() *DeadLetterConfig {
	if in == nil {
		return nil
	}
	out := new(DeadLetterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DestinationConfig) DeepCopyInto(out *DestinationConfig) {
	*out = *in
	if in.OnFailure != nil {
		in, out := &in.OnFailure, &out.OnFailure
		*out = new(OnFailure)
		(*in).DeepCopyInto(*out)
	}
	if in.OnSuccess != nil {
		in, out := &in.OnSuccess, &out.OnSuccess
		*out = new(OnSuccess)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DestinationConfig.
func (in *DestinationConfig) DeepCopy() *DestinationConfig {
	if in == nil {
		return nil
	}
	out := new(DestinationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Environment) DeepCopyInto(out *Environment) {
	*out = *in
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Environment.
func (in *Environment) DeepCopy() *Environment {
	if in == nil {
		return nil
	}
	out := new(Environment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentError) DeepCopyInto(out *EnvironmentError) {
	*out = *in
	if in.ErrorCode != nil {
		in, out := &in.ErrorCode, &out.ErrorCode
		*out = new(string)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentError.
func (in *EnvironmentError) DeepCopy() *EnvironmentError {
	if in == nil {
		return nil
	}
	out := new(EnvironmentError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentResponse) DeepCopyInto(out *EnvironmentResponse) {
	*out = *in
	if in.Error != nil {
		in, out := &in.Error, &out.Error
		*out = new(EnvironmentError)
		(*in).DeepCopyInto(*out)
	}
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentResponse.
func (in *EnvironmentResponse) DeepCopy() *EnvironmentResponse {
	if in == nil {
		return nil
	}
	out := new(EnvironmentResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EphemeralStorage) DeepCopyInto(out *EphemeralStorage) {
	*out = *in
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EphemeralStorage.
func (in *EphemeralStorage) DeepCopy() *EphemeralStorage {
	if in == nil {
		return nil
	}
	out := new(EphemeralStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventSourceMapping) DeepCopyInto(out *EventSourceMapping) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventSourceMapping.
func (in *EventSourceMapping) DeepCopy() *EventSourceMapping {
	if in == nil {
		return nil
	}
	out := new(EventSourceMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EventSourceMapping) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventSourceMappingConfiguration) DeepCopyInto(out *EventSourceMappingConfiguration) {
	*out = *in
	if in.AmazonManagedKafkaEventSourceConfig != nil {
		in, out := &in.AmazonManagedKafkaEventSourceConfig, &out.AmazonManagedKafkaEventSourceConfig
		*out = new(AmazonManagedKafkaEventSourceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.BatchSize != nil {
		in, out := &in.BatchSize, &out.BatchSize
		*out = new(int64)
		**out = **in
	}
	if in.BisectBatchOnFunctionError != nil {
		in, out := &in.BisectBatchOnFunctionError, &out.BisectBatchOnFunctionError
		*out = new(bool)
		**out = **in
	}
	if in.DestinationConfig != nil {
		in, out := &in.DestinationConfig, &out.DestinationConfig
		*out = new(DestinationConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.EventSourceARN != nil {
		in, out := &in.EventSourceARN, &out.EventSourceARN
		*out = new(string)
		**out = **in
	}
	if in.FilterCriteria != nil {
		in, out := &in.FilterCriteria, &out.FilterCriteria
		*out = new(FilterCriteria)
		(*in).DeepCopyInto(*out)
	}
	if in.FunctionARN != nil {
		in, out := &in.FunctionARN, &out.FunctionARN
		*out = new(string)
		**out = **in
	}
	if in.FunctionResponseTypes != nil {
		in, out := &in.FunctionResponseTypes, &out.FunctionResponseTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.LastModified != nil {
		in, out := &in.LastModified, &out.LastModified
		*out = (*in).DeepCopy()
	}
	if in.LastProcessingResult != nil {
		in, out := &in.LastProcessingResult, &out.LastProcessingResult
		*out = new(string)
		**out = **in
	}
	if in.MaximumBatchingWindowInSeconds != nil {
		in, out := &in.MaximumBatchingWindowInSeconds, &out.MaximumBatchingWindowInSeconds
		*out = new(int64)
		**out = **in
	}
	if in.MaximumRecordAgeInSeconds != nil {
		in, out := &in.MaximumRecordAgeInSeconds, &out.MaximumRecordAgeInSeconds
		*out = new(int64)
		**out = **in
	}
	if in.MaximumRetryAttempts != nil {
		in, out := &in.MaximumRetryAttempts, &out.MaximumRetryAttempts
		*out = new(int64)
		**out = **in
	}
	if in.ParallelizationFactor != nil {
		in, out := &in.ParallelizationFactor, &out.ParallelizationFactor
		*out = new(int64)
		**out = **in
	}
	if in.Queues != nil {
		in, out := &in.Queues, &out.Queues
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ScalingConfig != nil {
		in, out := &in.ScalingConfig, &out.ScalingConfig
		*out = new(ScalingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SelfManagedEventSource != nil {
		in, out := &in.SelfManagedEventSource, &out.SelfManagedEventSource
		*out = new(SelfManagedEventSource)
		(*in).DeepCopyInto(*out)
	}
	if in.SelfManagedKafkaEventSourceConfig != nil {
		in, out := &in.SelfManagedKafkaEventSourceConfig, &out.SelfManagedKafkaEventSourceConfig
		*out = new(SelfManagedKafkaEventSourceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SourceAccessConfigurations != nil {
		in, out := &in.SourceAccessConfigurations, &out.SourceAccessConfigurations
		*out = make([]*SourceAccessConfiguration, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(SourceAccessConfiguration)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.StartingPosition != nil {
		in, out := &in.StartingPosition, &out.StartingPosition
		*out = new(string)
		**out = **in
	}
	if in.StartingPositionTimestamp != nil {
		in, out := &in.StartingPositionTimestamp, &out.StartingPositionTimestamp
		*out = (*in).DeepCopy()
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.StateTransitionReason != nil {
		in, out := &in.StateTransitionReason, &out.StateTransitionReason
		*out = new(string)
		**out = **in
	}
	if in.Topics != nil {
		in, out := &in.Topics, &out.Topics
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TumblingWindowInSeconds != nil {
		in, out := &in.TumblingWindowInSeconds, &out.TumblingWindowInSeconds
		*out = new(int64)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventSourceMappingConfiguration.
func (in *EventSourceMappingConfiguration) DeepCopy() *EventSourceMappingConfiguration {
	if in == nil {
		return nil
	}
	out := new(EventSourceMappingConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventSourceMappingList) DeepCopyInto(out *EventSourceMappingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EventSourceMapping, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventSourceMappingList.
func (in *EventSourceMappingList) DeepCopy() *EventSourceMappingList {
	if in == nil {
		return nil
	}
	out := new(EventSourceMappingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EventSourceMappingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventSourceMappingSpec) DeepCopyInto(out *EventSourceMappingSpec) {
	*out = *in
	if in.AmazonManagedKafkaEventSourceConfig != nil {
		in, out := &in.AmazonManagedKafkaEventSourceConfig, &out.AmazonManagedKafkaEventSourceConfig
		*out = new(AmazonManagedKafkaEventSourceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.BatchSize != nil {
		in, out := &in.BatchSize, &out.BatchSize
		*out = new(int64)
		**out = **in
	}
	if in.BisectBatchOnFunctionError != nil {
		in, out := &in.BisectBatchOnFunctionError, &out.BisectBatchOnFunctionError
		*out = new(bool)
		**out = **in
	}
	if in.DestinationConfig != nil {
		in, out := &in.DestinationConfig, &out.DestinationConfig
		*out = new(DestinationConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EventSourceARN != nil {
		in, out := &in.EventSourceARN, &out.EventSourceARN
		*out = new(string)
		**out = **in
	}
	if in.FilterCriteria != nil {
		in, out := &in.FilterCriteria, &out.FilterCriteria
		*out = new(FilterCriteria)
		(*in).DeepCopyInto(*out)
	}
	if in.FunctionName != nil {
		in, out := &in.FunctionName, &out.FunctionName
		*out = new(string)
		**out = **in
	}
	if in.FunctionRef != nil {
		in, out := &in.FunctionRef, &out.FunctionRef
		*out = new(corev1alpha1.AWSResourceReferenceWrapper)
		(*in).DeepCopyInto(*out)
	}
	if in.FunctionResponseTypes != nil {
		in, out := &in.FunctionResponseTypes, &out.FunctionResponseTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.MaximumBatchingWindowInSeconds != nil {
		in, out := &in.MaximumBatchingWindowInSeconds, &out.MaximumBatchingWindowInSeconds
		*out = new(int64)
		**out = **in
	}
	if in.MaximumRecordAgeInSeconds != nil {
		in, out := &in.MaximumRecordAgeInSeconds, &out.MaximumRecordAgeInSeconds
		*out = new(int64)
		**out = **in
	}
	if in.MaximumRetryAttempts != nil {
		in, out := &in.MaximumRetryAttempts, &out.MaximumRetryAttempts
		*out = new(int64)
		**out = **in
	}
	if in.ParallelizationFactor != nil {
		in, out := &in.ParallelizationFactor, &out.ParallelizationFactor
		*out = new(int64)
		**out = **in
	}
	if in.QueueRefs != nil {
		in, out := &in.QueueRefs, &out.QueueRefs
		*out = make([]*corev1alpha1.AWSResourceReferenceWrapper, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.AWSResourceReferenceWrapper)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Queues != nil {
		in, out := &in.Queues, &out.Queues
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ScalingConfig != nil {
		in, out := &in.ScalingConfig, &out.ScalingConfig
		*out = new(ScalingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SelfManagedEventSource != nil {
		in, out := &in.SelfManagedEventSource, &out.SelfManagedEventSource
		*out = new(SelfManagedEventSource)
		(*in).DeepCopyInto(*out)
	}
	if in.SelfManagedKafkaEventSourceConfig != nil {
		in, out := &in.SelfManagedKafkaEventSourceConfig, &out.SelfManagedKafkaEventSourceConfig
		*out = new(SelfManagedKafkaEventSourceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SourceAccessConfigurations != nil {
		in, out := &in.SourceAccessConfigurations, &out.SourceAccessConfigurations
		*out = make([]*SourceAccessConfiguration, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(SourceAccessConfiguration)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.StartingPosition != nil {
		in, out := &in.StartingPosition, &out.StartingPosition
		*out = new(string)
		**out = **in
	}
	if in.StartingPositionTimestamp != nil {
		in, out := &in.StartingPositionTimestamp, &out.StartingPositionTimestamp
		*out = (*in).DeepCopy()
	}
	if in.Topics != nil {
		in, out := &in.Topics, &out.Topics
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TumblingWindowInSeconds != nil {
		in, out := &in.TumblingWindowInSeconds, &out.TumblingWindowInSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventSourceMappingSpec.
func (in *EventSourceMappingSpec) DeepCopy() *EventSourceMappingSpec {
	if in == nil {
		return nil
	}
	out := new(EventSourceMappingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventSourceMappingStatus) DeepCopyInto(out *EventSourceMappingStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.FunctionARN != nil {
		in, out := &in.FunctionARN, &out.FunctionARN
		*out = new(string)
		**out = **in
	}
	if in.LastModified != nil {
		in, out := &in.LastModified, &out.LastModified
		*out = (*in).DeepCopy()
	}
	if in.LastProcessingResult != nil {
		in, out := &in.LastProcessingResult, &out.LastProcessingResult
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.StateTransitionReason != nil {
		in, out := &in.StateTransitionReason, &out.StateTransitionReason
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventSourceMappingStatus.
func (in *EventSourceMappingStatus) DeepCopy() *EventSourceMappingStatus {
	if in == nil {
		return nil
	}
	out := new(EventSourceMappingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileSystemConfig) DeepCopyInto(out *FileSystemConfig) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.LocalMountPath != nil {
		in, out := &in.LocalMountPath, &out.LocalMountPath
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileSystemConfig.
func (in *FileSystemConfig) DeepCopy() *FileSystemConfig {
	if in == nil {
		return nil
	}
	out := new(FileSystemConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Filter) DeepCopyInto(out *Filter) {
	*out = *in
	if in.Pattern != nil {
		in, out := &in.Pattern, &out.Pattern
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Filter.
func (in *Filter) DeepCopy() *Filter {
	if in == nil {
		return nil
	}
	out := new(Filter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterCriteria) DeepCopyInto(out *FilterCriteria) {
	*out = *in
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]*Filter, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Filter)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterCriteria.
func (in *FilterCriteria) DeepCopy() *FilterCriteria {
	if in == nil {
		return nil
	}
	out := new(FilterCriteria)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Function) DeepCopyInto(out *Function) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Function.
func (in *Function) DeepCopy() *Function {
	if in == nil {
		return nil
	}
	out := new(Function)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Function) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionCode) DeepCopyInto(out *FunctionCode) {
	*out = *in
	if in.ImageURI != nil {
		in, out := &in.ImageURI, &out.ImageURI
		*out = new(string)
		**out = **in
	}
	if in.S3Bucket != nil {
		in, out := &in.S3Bucket, &out.S3Bucket
		*out = new(string)
		**out = **in
	}
	if in.S3BucketRef != nil {
		in, out := &in.S3BucketRef, &out.S3BucketRef
		*out = new(corev1alpha1.AWSResourceReferenceWrapper)
		(*in).DeepCopyInto(*out)
	}
	if in.S3Key != nil {
		in, out := &in.S3Key, &out.S3Key
		*out = new(string)
		**out = **in
	}
	if in.S3ObjectVersion != nil {
		in, out := &in.S3ObjectVersion, &out.S3ObjectVersion
		*out = new(string)
		**out = **in
	}
	if in.ZipFile != nil {
		in, out := &in.ZipFile, &out.ZipFile
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionCode.
func (in *FunctionCode) DeepCopy() *FunctionCode {
	if in == nil {
		return nil
	}
	out := new(FunctionCode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionCodeLocation) DeepCopyInto(out *FunctionCodeLocation) {
	*out = *in
	if in.ImageURI != nil {
		in, out := &in.ImageURI, &out.ImageURI
		*out = new(string)
		**out = **in
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
	if in.RepositoryType != nil {
		in, out := &in.RepositoryType, &out.RepositoryType
		*out = new(string)
		**out = **in
	}
	if in.ResolvedImageURI != nil {
		in, out := &in.ResolvedImageURI, &out.ResolvedImageURI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionCodeLocation.
func (in *FunctionCodeLocation) DeepCopy() *FunctionCodeLocation {
	if in == nil {
		return nil
	}
	out := new(FunctionCodeLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionConfiguration) DeepCopyInto(out *FunctionConfiguration) {
	*out = *in
	if in.Architectures != nil {
		in, out := &in.Architectures, &out.Architectures
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CodeSHA256 != nil {
		in, out := &in.CodeSHA256, &out.CodeSHA256
		*out = new(string)
		**out = **in
	}
	if in.CodeSize != nil {
		in, out := &in.CodeSize, &out.CodeSize
		*out = new(int64)
		**out = **in
	}
	if in.DeadLetterConfig != nil {
		in, out := &in.DeadLetterConfig, &out.DeadLetterConfig
		*out = new(DeadLetterConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = new(EnvironmentResponse)
		(*in).DeepCopyInto(*out)
	}
	if in.EphemeralStorage != nil {
		in, out := &in.EphemeralStorage, &out.EphemeralStorage
		*out = new(EphemeralStorage)
		(*in).DeepCopyInto(*out)
	}
	if in.FileSystemConfigs != nil {
		in, out := &in.FileSystemConfigs, &out.FileSystemConfigs
		*out = make([]*FileSystemConfig, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(FileSystemConfig)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.FunctionARN != nil {
		in, out := &in.FunctionARN, &out.FunctionARN
		*out = new(string)
		**out = **in
	}
	if in.FunctionName != nil {
		in, out := &in.FunctionName, &out.FunctionName
		*out = new(string)
		**out = **in
	}
	if in.Handler != nil {
		in, out := &in.Handler, &out.Handler
		*out = new(string)
		**out = **in
	}
	if in.ImageConfigResponse != nil {
		in, out := &in.ImageConfigResponse, &out.ImageConfigResponse
		*out = new(ImageConfigResponse)
		(*in).DeepCopyInto(*out)
	}
	if in.KMSKeyARN != nil {
		in, out := &in.KMSKeyARN, &out.KMSKeyARN
		*out = new(string)
		**out = **in
	}
	if in.LastModified != nil {
		in, out := &in.LastModified, &out.LastModified
		*out = new(string)
		**out = **in
	}
	if in.LastUpdateStatus != nil {
		in, out := &in.LastUpdateStatus, &out.LastUpdateStatus
		*out = new(string)
		**out = **in
	}
	if in.LastUpdateStatusReason != nil {
		in, out := &in.LastUpdateStatusReason, &out.LastUpdateStatusReason
		*out = new(string)
		**out = **in
	}
	if in.LastUpdateStatusReasonCode != nil {
		in, out := &in.LastUpdateStatusReasonCode, &out.LastUpdateStatusReasonCode
		*out = new(string)
		**out = **in
	}
	if in.Layers != nil {
		in, out := &in.Layers, &out.Layers
		*out = make([]*Layer, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Layer)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.MasterARN != nil {
		in, out := &in.MasterARN, &out.MasterARN
		*out = new(string)
		**out = **in
	}
	if in.MemorySize != nil {
		in, out := &in.MemorySize, &out.MemorySize
		*out = new(int64)
		**out = **in
	}
	if in.PackageType != nil {
		in, out := &in.PackageType, &out.PackageType
		*out = new(string)
		**out = **in
	}
	if in.RevisionID != nil {
		in, out := &in.RevisionID, &out.RevisionID
		*out = new(string)
		**out = **in
	}
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(string)
		**out = **in
	}
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(string)
		**out = **in
	}
	if in.SigningJobARN != nil {
		in, out := &in.SigningJobARN, &out.SigningJobARN
		*out = new(string)
		**out = **in
	}
	if in.SigningProfileVersionARN != nil {
		in, out := &in.SigningProfileVersionARN, &out.SigningProfileVersionARN
		*out = new(string)
		**out = **in
	}
	if in.SnapStart != nil {
		in, out := &in.SnapStart, &out.SnapStart
		*out = new(SnapStartResponse)
		(*in).DeepCopyInto(*out)
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.StateReason != nil {
		in, out := &in.StateReason, &out.StateReason
		*out = new(string)
		**out = **in
	}
	if in.StateReasonCode != nil {
		in, out := &in.StateReasonCode, &out.StateReasonCode
		*out = new(string)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(int64)
		**out = **in
	}
	if in.TracingConfig != nil {
		in, out := &in.TracingConfig, &out.TracingConfig
		*out = new(TracingConfigResponse)
		(*in).DeepCopyInto(*out)
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	if in.VPCConfig != nil {
		in, out := &in.VPCConfig, &out.VPCConfig
		*out = new(VPCConfigResponse)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionConfiguration.
func (in *FunctionConfiguration) DeepCopy() *FunctionConfiguration {
	if in == nil {
		return nil
	}
	out := new(FunctionConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionEventInvokeConfig) DeepCopyInto(out *FunctionEventInvokeConfig) {
	*out = *in
	if in.DestinationConfig != nil {
		in, out := &in.DestinationConfig, &out.DestinationConfig
		*out = new(DestinationConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.FunctionARN != nil {
		in, out := &in.FunctionARN, &out.FunctionARN
		*out = new(string)
		**out = **in
	}
	if in.LastModified != nil {
		in, out := &in.LastModified, &out.LastModified
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionEventInvokeConfig.
func (in *FunctionEventInvokeConfig) DeepCopy() *FunctionEventInvokeConfig {
	if in == nil {
		return nil
	}
	out := new(FunctionEventInvokeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionList) DeepCopyInto(out *FunctionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Function, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionList.
func (in *FunctionList) DeepCopy() *FunctionList {
	if in == nil {
		return nil
	}
	out := new(FunctionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FunctionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionSpec) DeepCopyInto(out *FunctionSpec) {
	*out = *in
	if in.Architectures != nil {
		in, out := &in.Architectures, &out.Architectures
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Code != nil {
		in, out := &in.Code, &out.Code
		*out = new(FunctionCode)
		(*in).DeepCopyInto(*out)
	}
	if in.CodeS3SHA256 != nil {
		in, out := &in.CodeS3SHA256, &out.CodeS3SHA256
		*out = new(string)
		**out = **in
	}
	if in.CodeSigningConfigARN != nil {
		in, out := &in.CodeSigningConfigARN, &out.CodeSigningConfigARN
		*out = new(string)
		**out = **in
	}
	if in.DeadLetterConfig != nil {
		in, out := &in.DeadLetterConfig, &out.DeadLetterConfig
		*out = new(DeadLetterConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = new(Environment)
		(*in).DeepCopyInto(*out)
	}
	if in.EphemeralStorage != nil {
		in, out := &in.EphemeralStorage, &out.EphemeralStorage
		*out = new(EphemeralStorage)
		(*in).DeepCopyInto(*out)
	}
	if in.FileSystemConfigs != nil {
		in, out := &in.FileSystemConfigs, &out.FileSystemConfigs
		*out = make([]*FileSystemConfig, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(FileSystemConfig)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Handler != nil {
		in, out := &in.Handler, &out.Handler
		*out = new(string)
		**out = **in
	}
	if in.ImageConfig != nil {
		in, out := &in.ImageConfig, &out.ImageConfig
		*out = new(ImageConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.KMSKeyARN != nil {
		in, out := &in.KMSKeyARN, &out.KMSKeyARN
		*out = new(string)
		**out = **in
	}
	if in.KMSKeyRef != nil {
		in, out := &in.KMSKeyRef, &out.KMSKeyRef
		*out = new(corev1alpha1.AWSResourceReferenceWrapper)
		(*in).DeepCopyInto(*out)
	}
	if in.Layers != nil {
		in, out := &in.Layers, &out.Layers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.MemorySize != nil {
		in, out := &in.MemorySize, &out.MemorySize
		*out = new(int64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PackageType != nil {
		in, out := &in.PackageType, &out.PackageType
		*out = new(string)
		**out = **in
	}
	if in.Publish != nil {
		in, out := &in.Publish, &out.Publish
		*out = new(bool)
		**out = **in
	}
	if in.ReservedConcurrentExecutions != nil {
		in, out := &in.ReservedConcurrentExecutions, &out.ReservedConcurrentExecutions
		*out = new(int64)
		**out = **in
	}
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(string)
		**out = **in
	}
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(string)
		**out = **in
	}
	if in.SnapStart != nil {
		in, out := &in.SnapStart, &out.SnapStart
		*out = new(SnapStart)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(int64)
		**out = **in
	}
	if in.TracingConfig != nil {
		in, out := &in.TracingConfig, &out.TracingConfig
		*out = new(TracingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.VPCConfig != nil {
		in, out := &in.VPCConfig, &out.VPCConfig
		*out = new(VPCConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionSpec.
func (in *FunctionSpec) DeepCopy() *FunctionSpec {
	if in == nil {
		return nil
	}
	out := new(FunctionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionStatus) DeepCopyInto(out *FunctionStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.CodeSHA256 != nil {
		in, out := &in.CodeSHA256, &out.CodeSHA256
		*out = new(string)
		**out = **in
	}
	if in.CodeSize != nil {
		in, out := &in.CodeSize, &out.CodeSize
		*out = new(int64)
		**out = **in
	}
	if in.ImageConfigResponse != nil {
		in, out := &in.ImageConfigResponse, &out.ImageConfigResponse
		*out = new(ImageConfigResponse)
		(*in).DeepCopyInto(*out)
	}
	if in.LastModified != nil {
		in, out := &in.LastModified, &out.LastModified
		*out = new(string)
		**out = **in
	}
	if in.LastUpdateStatus != nil {
		in, out := &in.LastUpdateStatus, &out.LastUpdateStatus
		*out = new(string)
		**out = **in
	}
	if in.LastUpdateStatusReason != nil {
		in, out := &in.LastUpdateStatusReason, &out.LastUpdateStatusReason
		*out = new(string)
		**out = **in
	}
	if in.LastUpdateStatusReasonCode != nil {
		in, out := &in.LastUpdateStatusReasonCode, &out.LastUpdateStatusReasonCode
		*out = new(string)
		**out = **in
	}
	if in.LayerStatuses != nil {
		in, out := &in.LayerStatuses, &out.LayerStatuses
		*out = make([]*Layer, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Layer)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.MasterARN != nil {
		in, out := &in.MasterARN, &out.MasterARN
		*out = new(string)
		**out = **in
	}
	if in.RevisionID != nil {
		in, out := &in.RevisionID, &out.RevisionID
		*out = new(string)
		**out = **in
	}
	if in.SigningJobARN != nil {
		in, out := &in.SigningJobARN, &out.SigningJobARN
		*out = new(string)
		**out = **in
	}
	if in.SigningProfileVersionARN != nil {
		in, out := &in.SigningProfileVersionARN, &out.SigningProfileVersionARN
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.StateReason != nil {
		in, out := &in.StateReason, &out.StateReason
		*out = new(string)
		**out = **in
	}
	if in.StateReasonCode != nil {
		in, out := &in.StateReasonCode, &out.StateReasonCode
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionStatus.
func (in *FunctionStatus) DeepCopy() *FunctionStatus {
	if in == nil {
		return nil
	}
	out := new(FunctionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionURLConfig) DeepCopyInto(out *FunctionURLConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionURLConfig.
func (in *FunctionURLConfig) DeepCopy() *FunctionURLConfig {
	if in == nil {
		return nil
	}
	out := new(FunctionURLConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FunctionURLConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionURLConfigList) DeepCopyInto(out *FunctionURLConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FunctionURLConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionURLConfigList.
func (in *FunctionURLConfigList) DeepCopy() *FunctionURLConfigList {
	if in == nil {
		return nil
	}
	out := new(FunctionURLConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FunctionURLConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionURLConfigSpec) DeepCopyInto(out *FunctionURLConfigSpec) {
	*out = *in
	if in.AuthType != nil {
		in, out := &in.AuthType, &out.AuthType
		*out = new(string)
		**out = **in
	}
	if in.CORS != nil {
		in, out := &in.CORS, &out.CORS
		*out = new(CORS)
		(*in).DeepCopyInto(*out)
	}
	if in.FunctionName != nil {
		in, out := &in.FunctionName, &out.FunctionName
		*out = new(string)
		**out = **in
	}
	if in.FunctionRef != nil {
		in, out := &in.FunctionRef, &out.FunctionRef
		*out = new(corev1alpha1.AWSResourceReferenceWrapper)
		(*in).DeepCopyInto(*out)
	}
	if in.Qualifier != nil {
		in, out := &in.Qualifier, &out.Qualifier
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionURLConfigSpec.
func (in *FunctionURLConfigSpec) DeepCopy() *FunctionURLConfigSpec {
	if in == nil {
		return nil
	}
	out := new(FunctionURLConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionURLConfigStatus) DeepCopyInto(out *FunctionURLConfigStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = new(string)
		**out = **in
	}
	if in.FunctionARN != nil {
		in, out := &in.FunctionARN, &out.FunctionARN
		*out = new(string)
		**out = **in
	}
	if in.FunctionURL != nil {
		in, out := &in.FunctionURL, &out.FunctionURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionURLConfigStatus.
func (in *FunctionURLConfigStatus) DeepCopy() *FunctionURLConfigStatus {
	if in == nil {
		return nil
	}
	out := new(FunctionURLConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionURLConfig_SDK) DeepCopyInto(out *FunctionURLConfig_SDK) {
	*out = *in
	if in.AuthType != nil {
		in, out := &in.AuthType, &out.AuthType
		*out = new(string)
		**out = **in
	}
	if in.CORS != nil {
		in, out := &in.CORS, &out.CORS
		*out = new(CORS)
		(*in).DeepCopyInto(*out)
	}
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = new(string)
		**out = **in
	}
	if in.FunctionARN != nil {
		in, out := &in.FunctionARN, &out.FunctionARN
		*out = new(string)
		**out = **in
	}
	if in.FunctionURL != nil {
		in, out := &in.FunctionURL, &out.FunctionURL
		*out = new(string)
		**out = **in
	}
	if in.LastModifiedTime != nil {
		in, out := &in.LastModifiedTime, &out.LastModifiedTime
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionURLConfig_SDK.
func (in *FunctionURLConfig_SDK) DeepCopy() *FunctionURLConfig_SDK {
	if in == nil {
		return nil
	}
	out := new(FunctionURLConfig_SDK)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageConfig) DeepCopyInto(out *ImageConfig) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.EntryPoint != nil {
		in, out := &in.EntryPoint, &out.EntryPoint
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.WorkingDirectory != nil {
		in, out := &in.WorkingDirectory, &out.WorkingDirectory
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageConfig.
func (in *ImageConfig) DeepCopy() *ImageConfig {
	if in == nil {
		return nil
	}
	out := new(ImageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageConfigError) DeepCopyInto(out *ImageConfigError) {
	*out = *in
	if in.ErrorCode != nil {
		in, out := &in.ErrorCode, &out.ErrorCode
		*out = new(string)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageConfigError.
func (in *ImageConfigError) DeepCopy() *ImageConfigError {
	if in == nil {
		return nil
	}
	out := new(ImageConfigError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageConfigResponse) DeepCopyInto(out *ImageConfigResponse) {
	*out = *in
	if in.Error != nil {
		in, out := &in.Error, &out.Error
		*out = new(ImageConfigError)
		(*in).DeepCopyInto(*out)
	}
	if in.ImageConfig != nil {
		in, out := &in.ImageConfig, &out.ImageConfig
		*out = new(ImageConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageConfigResponse.
func (in *ImageConfigResponse) DeepCopy() *ImageConfigResponse {
	if in == nil {
		return nil
	}
	out := new(ImageConfigResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Layer) DeepCopyInto(out *Layer) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.CodeSize != nil {
		in, out := &in.CodeSize, &out.CodeSize
		*out = new(int64)
		**out = **in
	}
	if in.SigningJobARN != nil {
		in, out := &in.SigningJobARN, &out.SigningJobARN
		*out = new(string)
		**out = **in
	}
	if in.SigningProfileVersionARN != nil {
		in, out := &in.SigningProfileVersionARN, &out.SigningProfileVersionARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Layer.
func (in *Layer) DeepCopy() *Layer {
	if in == nil {
		return nil
	}
	out := new(Layer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LayerVersion) DeepCopyInto(out *LayerVersion) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LayerVersion.
func (in *LayerVersion) DeepCopy() *LayerVersion {
	if in == nil {
		return nil
	}
	out := new(LayerVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LayerVersion) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LayerVersionContentInput) DeepCopyInto(out *LayerVersionContentInput) {
	*out = *in
	if in.S3Bucket != nil {
		in, out := &in.S3Bucket, &out.S3Bucket
		*out = new(string)
		**out = **in
	}
	if in.S3Key != nil {
		in, out := &in.S3Key, &out.S3Key
		*out = new(string)
		**out = **in
	}
	if in.S3ObjectVersion != nil {
		in, out := &in.S3ObjectVersion, &out.S3ObjectVersion
		*out = new(string)
		**out = **in
	}
	if in.ZipFile != nil {
		in, out := &in.ZipFile, &out.ZipFile
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LayerVersionContentInput.
func (in *LayerVersionContentInput) DeepCopy() *LayerVersionContentInput {
	if in == nil {
		return nil
	}
	out := new(LayerVersionContentInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LayerVersionContentOutput) DeepCopyInto(out *LayerVersionContentOutput) {
	*out = *in
	if in.CodeSHA256 != nil {
		in, out := &in.CodeSHA256, &out.CodeSHA256
		*out = new(string)
		**out = **in
	}
	if in.CodeSize != nil {
		in, out := &in.CodeSize, &out.CodeSize
		*out = new(int64)
		**out = **in
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
	if in.SigningJobARN != nil {
		in, out := &in.SigningJobARN, &out.SigningJobARN
		*out = new(string)
		**out = **in
	}
	if in.SigningProfileVersionARN != nil {
		in, out := &in.SigningProfileVersionARN, &out.SigningProfileVersionARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LayerVersionContentOutput.
func (in *LayerVersionContentOutput) DeepCopy() *LayerVersionContentOutput {
	if in == nil {
		return nil
	}
	out := new(LayerVersionContentOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LayerVersionList) DeepCopyInto(out *LayerVersionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LayerVersion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LayerVersionList.
func (in *LayerVersionList) DeepCopy() *LayerVersionList {
	if in == nil {
		return nil
	}
	out := new(LayerVersionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LayerVersionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LayerVersionSpec) DeepCopyInto(out *LayerVersionSpec) {
	*out = *in
	if in.CompatibleArchitectures != nil {
		in, out := &in.CompatibleArchitectures, &out.CompatibleArchitectures
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CompatibleRuntimes != nil {
		in, out := &in.CompatibleRuntimes, &out.CompatibleRuntimes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Content != nil {
		in, out := &in.Content, &out.Content
		*out = new(LayerVersionContentInput)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.LayerName != nil {
		in, out := &in.LayerName, &out.LayerName
		*out = new(string)
		**out = **in
	}
	if in.LicenseInfo != nil {
		in, out := &in.LicenseInfo, &out.LicenseInfo
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LayerVersionSpec.
func (in *LayerVersionSpec) DeepCopy() *LayerVersionSpec {
	if in == nil {
		return nil
	}
	out := new(LayerVersionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LayerVersionStatus) DeepCopyInto(out *LayerVersionStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.CreatedDate != nil {
		in, out := &in.CreatedDate, &out.CreatedDate
		*out = new(string)
		**out = **in
	}
	if in.LayerARN != nil {
		in, out := &in.LayerARN, &out.LayerARN
		*out = new(string)
		**out = **in
	}
	if in.VersionNumber != nil {
		in, out := &in.VersionNumber, &out.VersionNumber
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LayerVersionStatus.
func (in *LayerVersionStatus) DeepCopy() *LayerVersionStatus {
	if in == nil {
		return nil
	}
	out := new(LayerVersionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LayerVersionsListItem) DeepCopyInto(out *LayerVersionsListItem) {
	*out = *in
	if in.CompatibleArchitectures != nil {
		in, out := &in.CompatibleArchitectures, &out.CompatibleArchitectures
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CompatibleRuntimes != nil {
		in, out := &in.CompatibleRuntimes, &out.CompatibleRuntimes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CreatedDate != nil {
		in, out := &in.CreatedDate, &out.CreatedDate
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.LayerVersionARN != nil {
		in, out := &in.LayerVersionARN, &out.LayerVersionARN
		*out = new(string)
		**out = **in
	}
	if in.LicenseInfo != nil {
		in, out := &in.LicenseInfo, &out.LicenseInfo
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LayerVersionsListItem.
func (in *LayerVersionsListItem) DeepCopy() *LayerVersionsListItem {
	if in == nil {
		return nil
	}
	out := new(LayerVersionsListItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LayersListItem) DeepCopyInto(out *LayersListItem) {
	*out = *in
	if in.LatestMatchingVersion != nil {
		in, out := &in.LatestMatchingVersion, &out.LatestMatchingVersion
		*out = new(LayerVersionsListItem)
		(*in).DeepCopyInto(*out)
	}
	if in.LayerARN != nil {
		in, out := &in.LayerARN, &out.LayerARN
		*out = new(string)
		**out = **in
	}
	if in.LayerName != nil {
		in, out := &in.LayerName, &out.LayerName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LayersListItem.
func (in *LayersListItem) DeepCopy() *LayersListItem {
	if in == nil {
		return nil
	}
	out := new(LayersListItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OnFailure) DeepCopyInto(out *OnFailure) {
	*out = *in
	if in.Destination != nil {
		in, out := &in.Destination, &out.Destination
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OnFailure.
func (in *OnFailure) DeepCopy() *OnFailure {
	if in == nil {
		return nil
	}
	out := new(OnFailure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OnSuccess) DeepCopyInto(out *OnSuccess) {
	*out = *in
	if in.Destination != nil {
		in, out := &in.Destination, &out.Destination
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OnSuccess.
func (in *OnSuccess) DeepCopy() *OnSuccess {
	if in == nil {
		return nil
	}
	out := new(OnSuccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisionedConcurrencyConfigListItem) DeepCopyInto(out *ProvisionedConcurrencyConfigListItem) {
	*out = *in
	if in.FunctionARN != nil {
		in, out := &in.FunctionARN, &out.FunctionARN
		*out = new(string)
		**out = **in
	}
	if in.LastModified != nil {
		in, out := &in.LastModified, &out.LastModified
		*out = new(string)
		**out = **in
	}
	if in.StatusReason != nil {
		in, out := &in.StatusReason, &out.StatusReason
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisionedConcurrencyConfigListItem.
func (in *ProvisionedConcurrencyConfigListItem) DeepCopy() *ProvisionedConcurrencyConfigListItem {
	if in == nil {
		return nil
	}
	out := new(ProvisionedConcurrencyConfigListItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PutFunctionConcurrencyOutput) DeepCopyInto(out *PutFunctionConcurrencyOutput) {
	*out = *in
	if in.ReservedConcurrentExecutions != nil {
		in, out := &in.ReservedConcurrentExecutions, &out.ReservedConcurrentExecutions
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PutFunctionConcurrencyOutput.
func (in *PutFunctionConcurrencyOutput) DeepCopy() *PutFunctionConcurrencyOutput {
	if in == nil {
		return nil
	}
	out := new(PutFunctionConcurrencyOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingConfig) DeepCopyInto(out *ScalingConfig) {
	*out = *in
	if in.MaximumConcurrency != nil {
		in, out := &in.MaximumConcurrency, &out.MaximumConcurrency
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingConfig.
func (in *ScalingConfig) DeepCopy() *ScalingConfig {
	if in == nil {
		return nil
	}
	out := new(ScalingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfManagedEventSource) DeepCopyInto(out *SelfManagedEventSource) {
	*out = *in
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make(map[string][]*string, len(*in))
		for key, val := range *in {
			var outVal []*string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]*string, len(*in))
				for i := range *in {
					if (*in)[i] != nil {
						in, out := &(*in)[i], &(*out)[i]
						*out = new(string)
						**out = **in
					}
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfManagedEventSource.
func (in *SelfManagedEventSource) DeepCopy() *SelfManagedEventSource {
	if in == nil {
		return nil
	}
	out := new(SelfManagedEventSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfManagedKafkaEventSourceConfig) DeepCopyInto(out *SelfManagedKafkaEventSourceConfig) {
	*out = *in
	if in.ConsumerGroupID != nil {
		in, out := &in.ConsumerGroupID, &out.ConsumerGroupID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfManagedKafkaEventSourceConfig.
func (in *SelfManagedKafkaEventSourceConfig) DeepCopy() *SelfManagedKafkaEventSourceConfig {
	if in == nil {
		return nil
	}
	out := new(SelfManagedKafkaEventSourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapStart) DeepCopyInto(out *SnapStart) {
	*out = *in
	if in.ApplyOn != nil {
		in, out := &in.ApplyOn, &out.ApplyOn
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapStart.
func (in *SnapStart) DeepCopy() *SnapStart {
	if in == nil {
		return nil
	}
	out := new(SnapStart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapStartResponse) DeepCopyInto(out *SnapStartResponse) {
	*out = *in
	if in.ApplyOn != nil {
		in, out := &in.ApplyOn, &out.ApplyOn
		*out = new(string)
		**out = **in
	}
	if in.OptimizationStatus != nil {
		in, out := &in.OptimizationStatus, &out.OptimizationStatus
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapStartResponse.
func (in *SnapStartResponse) DeepCopy() *SnapStartResponse {
	if in == nil {
		return nil
	}
	out := new(SnapStartResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceAccessConfiguration) DeepCopyInto(out *SourceAccessConfiguration) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.URI != nil {
		in, out := &in.URI, &out.URI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceAccessConfiguration.
func (in *SourceAccessConfiguration) DeepCopy() *SourceAccessConfiguration {
	if in == nil {
		return nil
	}
	out := new(SourceAccessConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingConfig) DeepCopyInto(out *TracingConfig) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingConfig.
func (in *TracingConfig) DeepCopy() *TracingConfig {
	if in == nil {
		return nil
	}
	out := new(TracingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingConfigResponse) DeepCopyInto(out *TracingConfigResponse) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingConfigResponse.
func (in *TracingConfigResponse) DeepCopy() *TracingConfigResponse {
	if in == nil {
		return nil
	}
	out := new(TracingConfigResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCConfig) DeepCopyInto(out *VPCConfig) {
	*out = *in
	if in.SecurityGroupIDs != nil {
		in, out := &in.SecurityGroupIDs, &out.SecurityGroupIDs
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SecurityGroupRefs != nil {
		in, out := &in.SecurityGroupRefs, &out.SecurityGroupRefs
		*out = make([]*corev1alpha1.AWSResourceReferenceWrapper, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.AWSResourceReferenceWrapper)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.SubnetIDs != nil {
		in, out := &in.SubnetIDs, &out.SubnetIDs
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SubnetRefs != nil {
		in, out := &in.SubnetRefs, &out.SubnetRefs
		*out = make([]*corev1alpha1.AWSResourceReferenceWrapper, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.AWSResourceReferenceWrapper)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCConfig.
func (in *VPCConfig) DeepCopy() *VPCConfig {
	if in == nil {
		return nil
	}
	out := new(VPCConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCConfigResponse) DeepCopyInto(out *VPCConfigResponse) {
	*out = *in
	if in.SecurityGroupIDs != nil {
		in, out := &in.SecurityGroupIDs, &out.SecurityGroupIDs
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SubnetIDs != nil {
		in, out := &in.SubnetIDs, &out.SubnetIDs
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCConfigResponse.
func (in *VPCConfigResponse) DeepCopy() *VPCConfigResponse {
	if in == nil {
		return nil
	}
	out := new(VPCConfigResponse)
	in.DeepCopyInto(out)
	return out
}
