// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package layer_version

import (
	"context"
	"fmt"

	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrt "github.com/aws-controllers-k8s/runtime/pkg/runtime"
	acktypes "github.com/aws-controllers-k8s/runtime/pkg/types"
	s3apitypes "github.com/aws-controllers-k8s/s3-controller/apis/v1alpha1"

	svcapitypes "github.com/aws-controllers-k8s/lambda-controller/apis/v1alpha1"
)

// +kubebuilder:rbac:groups=s3.services.k8s.aws,resources=buckets,verbs=get;list
// +kubebuilder:rbac:groups=s3.services.k8s.aws,resources=buckets/status,verbs=get;list

// ClearResolvedReferences removes any reference values that were made
// concrete in the spec. It returns a copy of the input AWSResource which
// contains the original *Ref values, but none of their respective concrete
// values.
func (rm *resourceManager) ClearResolvedReferences(res acktypes.AWSResource) acktypes.AWSResource {
	ko := rm.concreteResource(res).ko.DeepCopy()

	if ko.Spec.Content != nil {
		if ko.Spec.Content.S3BucketRef != nil {
			ko.Spec.Content.S3Bucket = nil
		}
	}

	return &resource{ko}
}

// EnsureReferences restores, onto a copy of `latest`, the cross-resource
// reference (*Ref) fields it is missing, taking them from `desired`. Only
// reference fields are written, so every concrete value on `latest` stands.
//
// A *Ref is a sibling of the concrete field it resolves into, so rebuilding the
// containing struct from an AWS API response drops it. That disables
// ClearResolvedReferences, which suppresses a resolved value only while the
// sibling *Ref is visible, so the spec patch deletes the declared *Ref and stores
// the resolved value in its place.
//
// Only references reached through structs are restored. A top-level *Ref needs no
// help, since every write path starts from a DeepCopy of the object it was handed.
// A *Ref reached through a list is not restored and remains subject to the above:
// it has no fixed address, and replacing the whole list instead would discard
// whatever the service populated inside it.
//
// `desired` must be the declared resource with its references resolved, and must
// not be an object that has been through a resource manager: managers may mutate
// the resource they are handed, and some write API response values into it.
func (rm *resourceManager) EnsureReferences(
	desired acktypes.AWSResource,
	latest acktypes.AWSResource,
) acktypes.AWSResource {
	// Deep copy the source as well, so a reference handed over below does not
	// alias the caller's declared object.
	desiredKO := rm.concreteResource(desired).ko.DeepCopy()
	latestKO := rm.concreteResource(latest).ko.DeepCopy()

	if desiredKO.Spec.Content != nil && latestKO.Spec.Content != nil && desiredKO.Spec.Content.S3BucketRef != nil && latestKO.Spec.Content.S3BucketRef == nil {
		latestKO.Spec.Content.S3BucketRef = desiredKO.Spec.Content.S3BucketRef
	}

	return &resource{latestKO}
}

// ResolveReferences finds if there are any Reference field(s) present
// inside AWSResource passed in the parameter and attempts to resolve those
// reference field(s) into their respective target field(s). It returns a
// copy of the input AWSResource with resolved reference(s), a boolean which
// is set to true if the resource contains any references (regardless of if
// they are resolved successfully) and an error if the passed AWSResource's
// reference field(s) could not be resolved.
func (rm *resourceManager) ResolveReferences(
	ctx context.Context,
	apiReader client.Reader,
	res acktypes.AWSResource,
) (acktypes.AWSResource, bool, error) {
	ko := rm.concreteResource(res).ko

	resourceHasReferences := false
	err := validateReferenceFields(ko)
	if fieldHasReferences, err := rm.resolveReferenceForContent_S3Bucket(ctx, apiReader, ko); err != nil {
		return &resource{ko}, (resourceHasReferences || fieldHasReferences), err
	} else {
		resourceHasReferences = resourceHasReferences || fieldHasReferences
	}

	return &resource{ko}, resourceHasReferences, err
}

// validateReferenceFields validates the reference field and corresponding
// identifier field.
func validateReferenceFields(ko *svcapitypes.LayerVersion) error {

	if ko.Spec.Content != nil {
		if ko.Spec.Content.S3BucketRef != nil && ko.Spec.Content.S3Bucket != nil {
			return ackerr.ResourceReferenceAndIDNotSupportedFor("Content.S3Bucket", "Content.S3BucketRef")
		}
	}
	return nil
}

// resolveReferenceForContent_S3Bucket reads the resource referenced
// from Content.S3BucketRef field and sets the Content.S3Bucket
// from referenced resource. Returns a boolean indicating whether a reference
// contains references, or an error
func (rm *resourceManager) resolveReferenceForContent_S3Bucket(
	ctx context.Context,
	apiReader client.Reader,
	ko *svcapitypes.LayerVersion,
) (hasReferences bool, err error) {
	if ko.Spec.Content != nil {
		if ko.Spec.Content.S3BucketRef != nil && ko.Spec.Content.S3BucketRef.From != nil {
			hasReferences = true
			arr := ko.Spec.Content.S3BucketRef.From
			if arr.Name == nil || *arr.Name == "" {
				return hasReferences, fmt.Errorf("provided resource reference is nil or empty: Content.S3BucketRef")
			}
			namespace, err := ackrt.ResolveCrossNamespaceReference(
				ctx,
				rm.cfg.EnableCrossNamespace,
				&ko.Status.Conditions,
				ackrt.CrossNamespaceRefKindResource,
				ko.ObjectMeta.GetNamespace(),
				arr.Namespace,
				*arr.Name,
			)
			if err != nil {
				return hasReferences, err
			}
			obj := &s3apitypes.Bucket{}
			if err := getReferencedResourceState_Bucket(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
				return hasReferences, err
			}
			ko.Spec.Content.S3Bucket = (*string)(obj.Spec.Name)
		}
	}

	return hasReferences, nil
}

// getReferencedResourceState_Bucket looks up whether a referenced resource
// exists and is in a ACK.ResourceSynced=True state. If the referenced resource does exist and is
// in a Synced state, returns nil, otherwise returns `ackerr.ResourceReferenceTerminalFor` or
// `ResourceReferenceNotSyncedFor` depending on if the resource is in a Terminal state.
func getReferencedResourceState_Bucket(
	ctx context.Context,
	apiReader client.Reader,
	obj *s3apitypes.Bucket,
	name string, // the Kubernetes name of the referenced resource
	namespace string, // the Kubernetes namespace of the referenced resource
) error {
	namespacedName := types.NamespacedName{
		Namespace: namespace,
		Name:      name,
	}
	err := apiReader.Get(ctx, namespacedName, obj)
	if err != nil {
		return err
	}
	var refResourceTerminal bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeTerminal &&
			cond.Status == corev1.ConditionTrue {
			return ackerr.ResourceReferenceTerminalFor(
				"Bucket",
				namespace, name)
		}
	}
	if refResourceTerminal {
		return ackerr.ResourceReferenceTerminalFor(
			"Bucket",
			namespace, name)
	}
	var refResourceSynced bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeResourceSynced &&
			cond.Status == corev1.ConditionTrue {
			refResourceSynced = true
		}
	}
	if !refResourceSynced {
		return ackerr.ResourceReferenceNotSyncedFor(
			"Bucket",
			namespace, name)
	}
	if obj.Spec.Name == nil {
		return ackerr.ResourceReferenceMissingTargetFieldFor(
			"Bucket",
			namespace, name,
			"Spec.Name")
	}
	return nil
}
